### ISSUE TITLE
Problem using the Cadmium Shard : rror: can't find file 'Cadmium'

### ISSUE THREAD

**Issue by serge-hulne** [watzon/cadmium#36]
Hi, 
I am attempting to use the Cadmium Shard : https://github.com/cadmiumcr/cadmium

I have created a shard.yml file

```
name: tst
version: 0.1.0

authors:
  - serge <serge.hulne@gmail.com>

targets:
  tst:
    main: src/tst.cr

crystal: 1.2.2

license: MIT

dependencies:
  cadmium:
    github: cadmiumcr/cadmium
    branch: master
```

and here it the snippet of code (from the Cadmium doc) I'm trying to compile:
```
require "cadmium"

tokenizer = Cadmium.word_punctuation_tokenizer.new
tokenizer.tokenize("my dog hasn't any fleas.")
```

Yet, I get the error message:
```
In src/tst.cr:1:1

 1 | require "cadmium"
     ^
Error: can't find file 'cadmium'
```

NB: When running shards install, Cadmium seemed to install...
